name: spec-lint

on:
  pull_request:
    paths:
      - "specifications/**"
  push:
    branches:
      - "main"
    paths:
      - "specifications/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: specifications

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: specifications/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run spec lint
        run: npm run ci
